version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
